### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by mamutal91** [jirrezdex/jirrezdex.github.io#1]
Bom dia, onde conseguiu esse template?

**Comment by jirrezdex** [comment]
Boa tarde, este eu comprei pelo themeforest! Na verdade ele nem é assim! sofreu uma penca de modificações! E com a compra premium eu ganho direito de realocar os direitos autorais para mim!

**Comment by mamutal91** [comment]
Entendi, eu vi ele quando tinha uma home diferente, com umas animações. Tentando fazer download por falta de dinheiro, para meu fork aosp

**Comment by jirrezdex** [comment]
Sim! É realmente sai um pouquinho salgado! Mas poupa horas de trabalho caso não queira criar um do zero e procurar framewroks compátives com a ideia...
